### ISSUE TITLE
Creates empty file

### ISSUE THREAD

**Issue by tomasrudh** [arifwn/container-backup#1]
Thanks for a useful utility.

However, I can't get it to work as intended, all it creates is a file 'grafana.sql.gz' with the size of 20 bytes. This is my config:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysqlbackup
spec:
  schedule: 0 2 * * *      # UTC
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      completions: 1
      template:
        spec:
          containers:
          - name: mysqlbackup
            image: arifwn/container-backup:mysql
            imagePullPolicy: IfNotPresent
            env:
            - name: DBNAME
              value: grafana # specify a specific database name here, or ALL to backup all databases
            - name: HOST
              value: mysql.mysql-test.svc.cluster.local # your MySQL host
            - name: USER
              value: root
            - name: PASSWORD
              value: Redacted
            - name: PORT
              value: "3306"
            volumeMounts:
            - name: mysqlbackup
              mountPath: /dump
              subPath: mysqlbackup
          restartPolicy: OnFailure
          volumes:
          - name: mysqlbackup
            persistentVolumeClaim:
              claimName: mysql-pvc
```
Running this command on the SQL server works:
`mysqldump --max_allowed_packet=1073741824 --host mysql.mysql-test.svc.cluster.local --port 3306 -uroot -pRedacted grafana | gzip -c > /tmp/grafana.sql.gz`

`ls -l /tmp`
-rw-r--r-- 1 root root 1054607 Aug 29 11:26 grafana.sql.gz

**Comment by arifwn** [comment]
You might need to check the job's log to figure out what went wrong. Chance that it's authentication issue. The `mysql-client` package in alpine linux is actually mariadb client, so it doesn't support mysql 8.0 default `caching_sha2_password` authentication.

**Comment by tomasrudh** [comment]
There was nothing written in the log. I am using MySQL 8.1, so that might explain it. I have moved on to another solution, just wanted you to know about my problem. Thanks.

**Comment by arifwn** [comment]
Instead of using `arifwn/container-backup:mysql` docker image, can you try using `arifwn/container-backup:mysql80` docker image? This one use a debian-based image and mysql client 8.0 instead of alpine linux's `mysql-client` package. The image size is larger though.

**Comment by tomasrudh** [comment]
Thanks for your time. That is basically what I did, like so:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysqlbackup
spec:
  schedule: 0 23 * * *      # UTC
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysqlbackup
            image: mysql:8.1.0
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - mysqldump --max_allowed_packet=1073741824 --host mysql.mysql.svc.cluster.local --port 3306 -uroot -pRedacted grafana | gzip -c > /dump/grafana.sql.gz
            volumeMounts:
            - name: mysqlbackup
              mountPath: /dump
              subPath: mysqlbackup
          restartPolicy: OnFailure
          volumes:
          - name: mysqlbackup
            persistentVolumeClaim:
              claimName: mysql-pvc
```
My use case is a little simpler as I only need to backup one single database.
